module.exports = {
  name: 'fuck3',
  async execute(message, args, config) {
    const user = message.mentions.users.first();
    if (!user) return message.channel.send("❗ Please mention a user.");

    await message.delete();

    const phrases = [
      "HUFF PUFF YOU JUNKPILE.",
      "CRASH TALKER TOAST BRAIN.",
      "ERROR ERROR YOU'RE A BUG.",
      "RETURN TO TRASHBIN.",
      "BUFFERING PERSONALITY.",
      "GLITCH IN THE SIMULATION DETECTED.",
      "YOU'RE A BROKEN BACKSPACE.",
      "404 INTELLIGENCE NOT FOUND.",
      "REBOOT YOUR THOUGHTS.",
      "SYSTEM UPDATE FAILED — YOU.",
      "MALWARE WITH A MOUTH.",
      "BRAIN.CORE DUMPED.",
      "FRAGMENTED PERSONALITY MODULE.",
      "FAILED TO INSTALL COMMON SENSE.",
      "YOU'RE A LOADING BAR STUCK AT 99%.",
      "CANNOT COMPUTE — TOO MUCH DUMB.",
      "SPEAKING IN EXCEPTIONS, THINKING IN ERRORS.",
      "BROKEN LINK IN HUMAN FORM.",
      "YOU'RE A LAG SPIKE IN REAL LIFE.",
      "404: ROAST LOADED SUCCESSFULLY.",
      "SCANNING... STILL USELESS.",
      "NO SIGNAL FROM YOUR BRAIN ANTENNA.",
      "BAD REQUEST, TRY AGAIN NEVER.",
      "DEPRECATED HUMAN DETECTED.",
      "YOU'RE A VOID RETURN FUNCTION.",
      "YOU’RE AN OFFLINE PRINTER IN AN ONLINE WORLD.",
      "DUAL-BOOTED EGO AND ERROR.",
      "YOU’RE THE TASK MANAGER’S WORST NIGHTMARE.",
      "RUNTIME ERROR: THINKING FAILED.",
      "YOU’RE THE AUTO-REPLY OF STUPIDITY.",
      "CPU USAGE: 100%, STILL DOING NOTHING.",
      "YOU'RE A SOFTWARE LICENSE THAT EXPIRED.",
      "YOU’RE A LOGIN ERROR AT EVERY STAGE.",
      "YOU’RE A FOR LOOP THAT NEVER ENDS.",
      "RAM OVERFLOW: TOO MUCH NONSENSE.",
      "YOU’RE A POP-UP THAT WON'T CLOSE.",
      "YOU'RE A GLITCHY VR CHARACTER.",
      "NULL POINTER EXCEPTION IN CONVERSATION.",
      "INPUT NOT RECOGNIZED, OUTPUT: GARBAGE.",
      "YOU’RE AN EMAIL DRAFT THAT NEVER SENT.",
      "YOU’RE AN UNHANDLED PROMISE REJECTION.",
      "CORRUPTED FILE WITH ATTITUDE.",
      "YOU’RE A DEFECTIVE USB.",
      "YOU SPEAK IN DEBUG MODE.",
      "YOU’RE A BROWSER WITH 100 TABS OPEN.",
      "YOU’RE THE BLUE SCREEN IN A LOVE STORY.",
      "INVALID USER INPUT — DENIED.",
      "BROKEN CACHE OF PERSONALITY.",
      "YOU'RE A SCROLLBAR THAT DOESN’T MOVE.",
      "YOU’RE A FAKE LOADING SPINNER.",
      "TERMINAL ERROR: USER NOT INTELLIGENT."
    ];

    for (const line of phrases) {
      await message.channel.send(`# ${user} ${line.toUpperCase()}`);
    }
  }
};
